/* 
 * NativeBOINC - Native BOINC Client with Manager
 * Copyright (C) 2011, Mateusz Szpakowski
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

package edu.berkeley.boinc.lite;

/**
 * @author mat
 *
 */
public class Notice {
	public int seqno = -1;
    public String title = "";
    public String description = "";
    public double create_time;
    public double arrival_time;     // when item arrived at client
    public boolean is_private;
    public String category = "";
        // assigned by RSS source.  Reserved values:
        // "client": generated by client
        // "server": scheduler RPC message
    public String link = "";
        // URL where original message can be seen, if any
    public String project_name;
        // if notice is associated with a project

    // the following fields used in client only (not reported to GUI)
    public String guid = "";
    public String feed_url = "";
        // URL of RSS feed, or blank
    public boolean keep = false;
}
